Change style.yaml file.

diff --git a/.github/workflows/style.yaml b/.github/workflows/style.yaml
--- a/.github/workflows/style.yaml
+++ b/.github/workflows/style.yaml
@@ -1,114 +1,67 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: [devel, test, master]
-  pull_request:
-    branches: [devel, test, master]
+    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown", "**.[rR]nw"]
 
 name: Style
 
-concurrency:
-  group: style-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
-
 jobs:
   style:
-    name: Code Style
-    runs-on: ubuntu-20.04
-    if: >
-      !contains(github.event.commits[0].message, '[skip style]')
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      ##################### BEGIN boilerplate steps #####################
-      - name: Get branch names
-        id: branch-name
-        uses: tj-actions/branch-names@v5.4
-
-      - name: Checkout repo (PR) 🛎
+      - name: Checkout repo
         uses: actions/checkout@v3
-        if: github.event_name == 'pull_request'
         with:
-          ref: ${{ steps.branch-name.outputs.head_ref_branch }}
-          repository: ${{ github.event.pull_request.head.repo.full_name }}
-
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        if: github.event_name != 'pull_request'
-        with:
-          ref: ${{ steps.branch-name.outputs.head_ref_branch }}
-
-      - name: Normalize inputs
-        id: normalizer
-        run: |
-          R_VERSION="${{ inputs.r-version }}"
-          if [ "$R_VERSION" == "" ]
-          then {
-            R_VERSION="4.1.3"
-          }
-          fi
-          echo "R_VERSION=$R_VERSION" >> $GITHUB_OUTPUT
-        shell: bash
+          fetch-depth: 0
 
       - name: Setup R
         uses: r-lib/actions/setup-r@v2
         with:
-          r-version: ${{ steps.normalizer.outputs.R_VERSION }}
+          use-public-rspm: true
 
-      - name: Restore cache
+      - name: Install dependencies
+        uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          extra-packages: any::styler, any::roxygen2
+          needs: styler
+
+      - name: Enable styler cache
+        run: styler::cache_activate()
+        shell: Rscript {0}
+
+      - name: Determine cache location
+        id: styler-location
+        run: |
+          cat(
+            "location=",
+            styler::cache_info(format = "tabular")$location,
+            "\n",
+            file = Sys.getenv("GITHUB_OUTPUT"),
+            append = TRUE,
+            sep = ""
+          )
+        shell: Rscript {0}
+
+      - name: Cache styler
         uses: actions/cache@v3
         with:
-          path: |
-            ~/.local/share/renv
-            ~/.staged.dependencies
-          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
-          restore-keys: ${{ runner.os }}-renv-
-
-      - name: Run Staged dependencies
-        uses: insightsengineering/staged-dependencies-action@v1
-        with:
-          run-system-dependencies: true
-          enable-check: false
-        env:
-          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-          USE_RENV: "FALSE"
-      ##################### END boilerplate steps #####################
-
-      - name: Get changed files
-        id: changed-files
-        uses: Ana06/get-changed-files@v2.1.0
-        with:
-          format: csv
-          filter: |
-            *
-            !renv/*.R
-      - name: Run styler
-        run: |
-          changed_files <- unlist(strsplit(
-            "${{ steps.changed-files.outputs.all }}",
-            split=","
-          ))
-          is_r_file <- function(x) {
-              ext <- tools::file_ext(x)
-              ext %in% c("R", "Rmd", "Rnw", "Rmarkdown", "qmd")
-          }
-          changed_r_files <- Filter(is_r_file, changed_files)
-          changed_r_files <- Filter(file.exists, changed_r_files)
-          detect <- styler::style_file(changed_r_files, dry = "on")
-          if (TRUE %in% detect$changed) {
-            problems <- subset(detect$file, detect$changed == T)
-            cat(paste(
-              "☠ One or more files had styling errors.",
-              "Please see the log above for remediations,",
-              "or simply run the following commands",
-              "for an immediate fix:\n"
-            ))
-            cat("────────────────────────────────────────\n")
-            cat(paste0(
-              "styler::style_file(", capture.output(dput(problems)), ")\n"
-            ))
-            cat("────────────────────────────────────────\n")
-            cat("⚠️ Here is the complete git diff for the files that changed:\n")
-            system("git diff")
-            cat("────────────────────────────────────────\n")
-            cat(paste("ℹ️ Version of styler used in this workflow:", packageVersion("styler")))
-            quit(status = length(problems))
-          }
+          path: ${{ steps.styler-location.outputs.location }}
+          key: ${{ runner.os }}-styler-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-styler-
+            ${{ runner.os }}-
+      - name: Style
+        run: styler::style_pkg(filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"))
         shell: Rscript {0}
+
+      - name: Commit and push changes
+        run: |
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git add R/\*
+          git commit -m "Style code" || echo "No changes to commit"
+          git pull --ff-only
+          git push origin
